[workspace]
members = [
    "aggregator",
    "call-home",
    "console-logger",
    "exporter",
    "k8s/plugin",
    "k8s/proxy",
    "k8s/supportability",
    "k8s/upgrade-job",
]

exclude = [ "./dependencies/control-plane" ]
